### ISSUE TITLE
wap to create a dictionary find the lngth of the dctnry nd perform below operations 

### ISSUE THREAD

**Issue by rusher-md** [rusher-md/learning-python#4]

**Comment by Adnan0o7** [comment]
- Length of the dictionary should be 10
- Add a key\value pair 
- Remove first element
- add element in the middle of dict
- print all elements of the dictionary
-  print all keys of the dictionary
-  print all values of the dict and convert them into a list
- reverse the above list

**Comment by Adnan0o7** [comment]
git add -A
git commit -m "update"
git push

**Comment by Adnan0o7** [comment]
Done
