### ISSUE TITLE
wap makw dict lst tup reverse each other convert each other convert all of them print individual element same for tup lst dict print the middle element

### ISSUE THREAD

**Issue by rusher-md** [rusher-md/learning-python#6]

**Comment by Adnan0o7** [comment]
- convert list to tuple, duct
 - convert dict to list, tuple
 - convert tuple to list, dict
 - print all elements for list, tuple and dict
 - print middle element for list, tuple and dict

**Comment by Adnan0o7** [comment]
- reverse dict, tuple, list

**Comment by Adnan0o7** [comment]
The dictionary is a different data type.
 Tuples and lists cannot be converted into a dict directly.
 
 Refer to the below diagram:
 
<img width="710" alt="image" src="https://github.com/rusher-md/learning-python/assets/18405983/b53e2e5f-e36e-4737-9353-2e3d59fbfc83">
