### ISSUE TITLE
Perform operations on the below nested list

### ISSUE THREAD

**Issue by Adnan0o7** [rusher-md/learning-python#8]
Us the below nested list for this question 

nested_list = [{1:'2', 2:'3' }, [1,24], [12,3,4], 'adnan']

**Comment by Adnan0o7** [comment]
- Add a list at the last index of the given nested list

- Delete the middle element of the nested list

- Print all element of the last added nested list

- add an element of integer type to the end of the nested list

- reverse the nested list

- add a dict with 3 key value pairs to the start of the nested list

- find the length of the nested list

**Comment by Adnan0o7** [comment]
@rusher-md  Print all elements of the last added nested list is missing from the answer

**Comment by rusher-md** [comment]
updated
